version: "3.9"
   
services:
  build_environ:
    build:
      context: "."
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    command: ./build_for_linux.sh
    volumes:
      - .:/build
